
export const AVATARS = [
  'https://avataaars.io/?avatarStyle=Circle&topType=LongHairBob&accessoriesType=Sunglasses&hairColor=Platinum&facialHairType=BeardMajestic&facialHairColor=BrownDark&clotheType=ShirtCrewNeck&clotheColor=Heather&eyeType=Close&eyebrowType=DefaultNatural&mouthType=Smile&skinColor=Black',
  'https://avataaars.io/?avatarStyle=Circle&topType=ShortHairShortWaved&accessoriesType=Round&hairColor=Blonde&facialHairType=MoustacheFancy&facialHairColor=Blonde&clotheType=BlazerSweater&eyeType=Side&eyebrowType=RaisedExcitedNatural&mouthType=Sad&skinColor=Tanned',
  'https://avataaars.io/?avatarStyle=Circle&topType=LongHairBob&accessoriesType=Round&hairColor=Red&facialHairType=BeardMajestic&facialHairColor=Platinum&clotheType=ShirtVNeck&clotheColor=PastelRed&eyeType=Wink&eyebrowType=SadConcerned&mouthType=Twinkle&skinColor=Pale',
  'https://avataaars.io/?avatarStyle=Circle&topType=LongHairStraightStrand&accessoriesType=Prescription01&hairColor=BlondeGolden&facialHairType=Blank&facialHairColor=Auburn&clotheType=Hoodie&clotheColor=PastelOrange&eyeType=Surprised&eyebrowType=UpDown&mouthType=Grimace&skinColor=Brown',
  'https://avataaars.io/?avatarStyle=Circle&topType=ShortHairShaggyMullet&accessoriesType=Wayfarers&hairColor=Black&facialHairType=Blank&facialHairColor=BlondeGolden&clotheType=GraphicShirt&clotheColor=Red&graphicType=Bat&eyeType=WinkWacky&eyebrowType=Default&mouthType=Disbelief&skinColor=Pale',
  'https://avataaars.io/?avatarStyle=Circle&topType=LongHairShavedSides&accessoriesType=Sunglasses&hairColor=SilverGray&facialHairType=MoustacheMagnum&facialHairColor=Auburn&clotheType=ShirtCrewNeck&clotheColor=PastelOrange&eyeType=Dizzy&eyebrowType=FlatNatural&mouthType=Tongue&skinColor=Light',
  'https://avataaars.io/?avatarStyle=Circle&topType=LongHairStraightStrand&accessoriesType=Kurt&hairColor=Black&facialHairType=BeardLight&facialHairColor=Black&clotheType=Hoodie&clotheColor=PastelGreen&eyeType=Default&eyebrowType=RaisedExcitedNatural&mouthType=Concerned&skinColor=Yellow',
  'https://avataaars.io/?avatarStyle=Circle&topType=LongHairStraightStrand&accessoriesType=Kurt&hairColor=Black&facialHairType=BeardLight&facialHairColor=Black&clotheType=Hoodie&clotheColor=PastelGreen&eyeType=Default&eyebrowType=RaisedExcitedNatural&mouthType=Concerned&skinColor=Yellow',
  'https://avataaars.io/?avatarStyle=Circle&topType=WinterHat2&accessoriesType=Round&hatColor=PastelOrange&hairColor=Red&facialHairType=MoustacheMagnum&facialHairColor=BrownDark&clotheType=ShirtCrewNeck&clotheColor=White&eyeType=Surprised&eyebrowType=DefaultNatural&mouthType=ScreamOpen&skinColor=Black',
  'https://avataaars.io/?avatarStyle=Circle&topType=WinterHat2&accessoriesType=Round&hatColor=PastelOrange&hairColor=Red&facialHairType=MoustacheMagnum&facialHairColor=BrownDark&clotheType=ShirtCrewNeck&clotheColor=White&eyeType=Surprised&eyebrowType=DefaultNatural&mouthType=ScreamOpen&skinColor=Black',
  'https://avataaars.io/?avatarStyle=Circle&topType=LongHairFroBand&accessoriesType=Wayfarers&hatColor=PastelGreen&hairColor=BrownDark&facialHairType=BeardLight&facialHairColor=Platinum&clotheType=ShirtCrewNeck&clotheColor=White&eyeType=Cry&eyebrowType=RaisedExcited&mouthType=Concerned&skinColor=Tanned',
  'https://avataaars.io/?avatarStyle=Circle&topType=LongHairBigHair&accessoriesType=Prescription01&hairColor=Red&facialHairType=BeardMedium&facialHairColor=BrownDark&clotheType=BlazerShirt&eyeType=Cry&eyebrowType=FlatNatural&mouthType=ScreamOpen&skinColor=Black',
];